### ISSUE TITLE
Export path hardcoded to /tmp does not work on windows

### ISSUE THREAD

**Issue by mborejdo** [vihu/gogo#7]
As the title states. Would be great, if we could just store it locally?

**Comment by vihu** [comment]
Oh geez, thanks for bringing this up. I completely ignored the fact that people might be using this on Windows. Thankfully the fix is simple enough but I need to reshuffle the tags a bit to make the transition to `v2.0.*` easier.

So:
- I will fix the hardcoded path and allow users to specify a path on `export`
- I will introduce a `v1.0.2` still using rocksdb backend with the export path fix, just so people can still export their old databases to csv.
- Finally I will bump to `v2.0.1` with the export path fix (and some other housekeeping stuff as well).
